issue: 16
title: "UI/UX改善: 細かな機能修正"
description: |
  細かな機能修正
  - サイドバーを閉じるボタンがわかりにくい。サイドバーを閉じた時に閉じれていない。アイコンが半分くらい写っている
  - Dashboard
    - Daily Spendingが0ドルなのに昨日とくらべて12.5%と表示されている。計算があっているか確認
    - Total Videosはどの期間の話なのかわかりにくい。
    - Recent Transcriptionsに過去のものが表示されていない。Error loading history: Failed to fetch history
    - Quick Upload欄に直接URLを入力できて、推論ができるようにしてほしい。ボタンを押すとUpload画面に移動するのはめんどくさい
  - Upload video
    - URLを入力して、推論をするとエラーが出る。
  - settings
    - prompt settingsにデフォルトのプロンプトが表示されていない。
    - defalut languageが日本語になっている。デフォルトにしてほしい。あとなんの言語設定なのか分かりにくい。
type: "Bug"
state: Design
design: tasks/design/16_Bug.md
createdAt: "2025-07-03T06:12:40Z"
updatedAt: "2025-07-03T06:18:30Z"