issue: 18
title: "動画ファイル対応: MOV/MP4形式の動画解析サポート"
description: |
  youtubeの動画のみではなく、movやmp4などの動画ファイルも対象にいれ、同様の解析ができるようにする
type: Feature
state: Dev
design: tasks/design/18_Feature.md
implementation:
  branch: feature/implement-18
  commits:
    - hash: e54064fbb81899da990536dffe3a6e7eb4968cb8
      message: "fix: Replace MP3 codec with PCM WAV for universal audio extraction compatibility"
      timestamp: "2025-07-10T11:00:00Z"
    - hash: c0f1a0b
      message: "feat: Add video playback support for uploaded MOV/MP4 files"
      timestamp: "2025-07-10T20:37:00Z"
    - hash: 2da25e5
      message: "fix: Resolve video playbook and blob URL issues for uploaded files"
      timestamp: "2025-07-10T20:45:00Z"
    - hash: cd2c006
      message: "fix: Resolve video analysis and playback issues for MP4/MOV files"
      timestamp: "2025-07-10T23:55:00Z"
    - hash: 855f7f1
      message: "fix: Prioritize local video playback over YouTube for MOV/MP4 files"
      timestamp: "2025-07-11T00:05:00Z"
    - hash: 4bd29df
      message: "feat: Add pre-analysis cost estimation for videos and YouTube URLs"
      timestamp: "2025-07-11T00:10:00Z"
    - hash: 2cdd47c
      message: "fix: Improve cost estimation timing and debugging for URL input"
      timestamp: "2025-07-11T00:15:00Z"
    - hash: 7187266
      message: "fix: Enhance error handling and debugging for cost estimation API"
      timestamp: "2025-07-11T00:25:03Z"
    - hash: 07b6def
      message: "feat: Add GPT model display and auto-recalculation for cost estimation"
      timestamp: "2025-07-11T00:40:36Z"
    - hash: 00aee05
      message: "feat: Add GPT-4.1 models (nano, mini, advanced) to model selection dropdown"
      timestamp: "2025-07-10T15:53:47Z"
    - hash: 3e4020c
      message: "feat: Add pricing information to model selection dropdown"
      timestamp: "2025-07-10T16:01:30Z"
    - hash: bccf794
      message: "fix: Correct GPT model pricing to match OpenAI official rates"
      timestamp: "2025-07-10T16:11:09Z"
    - hash: 16f3ecf
      message: "feat: Replace standard GPT models with GPT-4.1 series"
      timestamp: "2025-07-10T17:34:33Z"
    - hash: 62f1d61
      message: "fix: Remove non-existent GPT-4.1 models and restore valid OpenAI models"
      timestamp: "2025-07-11T04:03:00Z"
    - hash: 4697d98
      message: "fix: Fix Response body stream already read error in cost estimation"
      timestamp: "2025-07-11T04:30:00Z"
    - hash: 50753cb
      message: "feat: Add transcription model selection with GPT-4o-Transcribe, GPT-4o-Mini-Transcribe, and Whisper-1"
      timestamp: "2025-07-11T18:23:00Z"
    - hash: 12ca619
      message: "fix: Improve transcription model UI layout and label width"
      timestamp: "2025-07-11T20:16:51Z"
    - hash: 623e667
      message: "feat: Improve cost estimation display and clarify model usage labels"
      timestamp: "2025-07-11T20:23:27Z"
    - hash: 45f7357
      message: "fix: Align form elements by adjusting label heights and text"
      timestamp: "2025-07-11T20:28:26Z"
    - hash: 3a273c2
      message: "fix: Prevent text truncation in form labels with proper overflow handling"
      timestamp: "2025-07-11T20:31:42Z"
    - hash: e06ea47
      message: "feat: Improve form layout with descriptive labels and separate button row"
      timestamp: "2025-07-11T20:35:30Z"
    - hash: fff8dbd
      message: "fix: Set default transcription model to GPT-4o and fix audio token estimation"
      timestamp: "2025-07-11T20:40:58Z"
    - hash: 46be570
      message: "fix: Improve input type button visibility for unselected state"
      timestamp: "2025-07-11T20:44:13Z"
    - hash: aad66f1
      message: "fix: Dramatically improve input type button contrast and visibility"
      timestamp: "2025-07-11T20:47:42Z"
    - hash: 4e4cccc
      message: "fix: Maximize input type button contrast with white background and clear borders"
      timestamp: "2025-07-11T20:51:21Z"
    - hash: ca8308b
      message: "fix: Keep selected input type button blue on hover"
      timestamp: "2025-07-11T20:54:13Z"
    - hash: 3dc80dd
      message: "feat: Add processing time estimation and analysis progress visualization"
      timestamp: "2025-07-11T21:06:41Z"
    - hash: e28d554
      message: "fix: Improve analysis progress visibility and enhance UI design"
      timestamp: "2025-07-11T21:20:19Z"
    - hash: 611c646
      message: "fix: Correct processing time display to match total calculation"
      timestamp: "2025-07-11T16:49:00Z"
    - hash: 28248eb
      message: "feat: Add historical data-based summary time estimation"
      timestamp: "2025-07-11T17:04:00Z"
    - hash: 2097958
      message: "feat: Display processing rates per minute instead of absolute times"
      timestamp: "2025-07-11T17:12:00Z"
    - hash: 7591b7d
      message: "feat: Add individual transcription/summary time display in Data Insights"
      timestamp: "2025-07-11T17:25:00Z"
    - hash: b229719
      message: "feat: Show only normalized processing times in Analysis page"
      timestamp: "2025-07-11T17:31:00Z"
    - hash: 9f2aa0b
      message: "fix: Use getTranscriptionResponseFormat helper for all transcription API calls"
      timestamp: "2025-07-12T13:00:38Z"
    - hash: 717a448
      message: "docs: Add documentation for GPT-4o-transcribe response format fix"
      timestamp: "2025-07-12T13:12:06Z"
    - hash: 60c7a92
      message: "feat: Ensure timestamp support for video file transcriptions"
      timestamp: "2025-07-12T19:16:42Z"
    - hash: d93ba61
      message: "fix: Add video player support for uploaded MOV/MP4 files"
      timestamp: "2025-07-12T19:46:14Z"
    - hash: c0b4aba
      message: "fix: Distinguish between YouTube videos and uploaded files in video player"
      timestamp: "2025-07-12T19:57:46Z"
    - hash: f947e6e
      message: "fix: Unify color intensity between cost and processing time displays"
      timestamp: "2025-07-13T00:00:00Z"
    - hash: b89f2f7
      message: "fix: Improve processing time display format to be more intuitive"
      timestamp: "2025-07-13T00:10:00Z"
createdAt: "2025-07-10T10:24:21Z"
updatedAt: "2025-07-13T00:10:00Z"
