issue: 28
title: 'fix: improve error handling in /api/summarize endpoint'
description: |
  /api/summarize エンドポイントのエラーハンドリングが不適切で、実際のエラー原因がユーザーに伝わらない。
  下記のエラーも出ており、今まで動いていた動作が動かない。
  Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
  /api/summarize:1  Failed to load resource: the server responded with a status of 503 ()Understand this error
  index-6tE7dN4Y.js:179 Summary generation failed: 503 {"error":"⚠️ 要約の生成に失敗しました。APIの利用制限に達している可能性があります。"}
  HE.console.error @ index-6tE7dN4Y.js:179Understand this error
  index-6tE7dN4Y.js:179 Error generating summary: Error: Failed to generate summary: 503
type: Bug
state: Review
design: tasks/design/28_Bug.md
implementation:
  branch: feature/implement-28
  commits:
    - 754cdbeadf663dcfdae1d1c8990063b5767f204e
    - 4661a3067890c8fa4f6f4f1f6e8b0f5a9c3e7d2a
    - d8b0440b9f3b7c8e5a4d3f2e1c9b8a7d6c5b4a3
    - 982438882f5e6d4c3b2a1f9e8d7c6b5a4f3e2d1
    - 99fbec5a3c2b1d9e8f7a6b5c4d3e2f1a0b9c8d7
    - 80cc8f0d7e6c5b4a3f2e1d0c9b8a7f6e5d4c3b2
    - 3686f20e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0
  files:
    - src/server.ts
    - src/components/shared/TranscriptViewer.tsx
    - src/components/pages/AnalyzePage.tsx
    - src/types/index.ts
    - src/services/youtube-api.ts
    - docs/youtube-api-setup.md
    - docs/terms-and-compliance.md
    - .env.example
    - tests/api/summarize-error-handling.test.ts
pr:
  number: 30
  url: https://github.com/boku-miyaji/youtube_translater/pull/30
  description: tasks/pr/28_Bug.md
  review: tasks/pr/28_Bug_review.md
  status: tasks/pr/28_Bug_status.md
  commits: tasks/pr/28_commits/
createdAt: '2025-10-30T14:38:26Z'
updatedAt: '2025-11-01T13:14:08Z'
